### ISSUE TITLE
Rating001Test throws Exception

### ISSUE THREAD

**Issue by christophs78** [primefaces-extensions/primefaces-integration-tests#93]
Seems to be browser-independent:
```
2021-01-11T15:31:46.2825780Z java.lang.NumberFormatException: For input string: "def"
2021-01-11T15:31:46.2927700Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2021-01-11T15:31:46.3028100Z 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
2021-01-11T15:31:46.3130730Z 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
2021-01-11T15:31:46.3232290Z 	at org.primefaces.component.rating.RatingRenderer.decode(RatingRenderer.java:50)
2021-01-11T15:31:46.3333460Z 	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:479)
2021-01-11T15:31:46.3436190Z 	at javax.faces.component.UIInput.decode(UIInput.java:371)
2021-01-11T15:31:46.3537220Z 	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1408)
```

Our test does not recognise this server-error yet. 
So maybe two issues. a) fix the test and b) look how our integration-tests fail when a server-side-exception is thrown
Hm. Is this error for this test - works as (test is) designed?

**Comment by christophs78** [comment]
Full log:

```
2021-01-11T15:34:07.9150160Z Jan 11, 2021 3:34:07 PM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
2021-01-11T15:34:07.9189930Z SEVERE: For input string: "def"
2021-01-11T15:34:07.9209140Z java.lang.NumberFormatException: For input string: "def"
2021-01-11T15:34:07.9211360Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2021-01-11T15:34:07.9219020Z 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
2021-01-11T15:34:07.9221080Z 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
2021-01-11T15:34:07.9229040Z 	at org.primefaces.component.rating.RatingRenderer.decode(RatingRenderer.java:50)
2021-01-11T15:34:07.9233730Z 	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:479)
2021-01-11T15:34:07.9235360Z 	at javax.faces.component.UIInput.decode(UIInput.java:371)
2021-01-11T15:34:07.9237030Z 	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1408)
2021-01-11T15:34:07.9239000Z 	at javax.faces.component.UIInput.processDecodes(UIInput.java:207)
2021-01-11T15:34:07.9240600Z 	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
2021-01-11T15:34:07.9242360Z 	at javax.faces.component.UIForm.processDecodes(UIForm.java:154)
2021-01-11T15:34:07.9243940Z 	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
2021-01-11T15:34:07.9246080Z 	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
2021-01-11T15:34:07.9247700Z 	at javax.faces.component.UIViewRoot._processDecodesDefault(UIViewRoot.java:1772)
2021-01-11T15:34:07.9248940Z 	at javax.faces.component.UIViewRoot.access$500(UIViewRoot.java:81)
2021-01-11T15:34:07.9250830Z 	at javax.faces.component.UIViewRoot$ApplyRequestValuesPhaseProcessor.process(UIViewRoot.java:1863)
2021-01-11T15:34:07.9252320Z 	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
2021-01-11T15:34:07.9254020Z 	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:942)
2021-01-11T15:34:07.9256080Z 	at org.apache.myfaces.lifecycle.ApplyRequestValuesExecutor.execute(ApplyRequestValuesExecutor.java:42)
2021-01-11T15:34:07.9258330Z 	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
2021-01-11T15:34:07.9260160Z 	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
2021-01-11T15:34:07.9262210Z 	at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:57)
2021-01-11T15:34:07.9271890Z 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
2021-01-11T15:34:07.9273770Z 	at org.apache.tomee.myfaces.TomEEWorkaroundFacesServlet.service(TomEEWorkaroundFacesServlet.java:47)
2021-01-11T15:34:07.9276250Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2021-01-11T15:34:07.9278570Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9281420Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2021-01-11T15:34:07.9283650Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-01-11T15:34:07.9286730Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9288550Z 	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
2021-01-11T15:34:07.9290610Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-01-11T15:34:07.9293000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9295020Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2021-01-11T15:34:07.9296920Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2021-01-11T15:34:07.9298570Z 	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
2021-01-11T15:34:07.9300330Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2021-01-11T15:34:07.9302200Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
2021-01-11T15:34:07.9304140Z 	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
2021-01-11T15:34:07.9306080Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2021-01-11T15:34:07.9307850Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2021-01-11T15:34:07.9309600Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2021-01-11T15:34:07.9311200Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
2021-01-11T15:34:07.9312850Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2021-01-11T15:34:07.9314490Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
2021-01-11T15:34:07.9315960Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
2021-01-11T15:34:07.9317530Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2021-01-11T15:34:07.9319310Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-11T15:34:07.9320960Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-11T15:34:07.9322520Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2021-01-11T15:34:07.9324010Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-11T15:34:07.9324600Z 
2021-01-11T15:34:07.9328490Z Jan 11, 2021 3:34:07 PM org.primefaces.application.exceptionhandler.PrimeExceptionHandler handle
2021-01-11T15:34:07.9329900Z SEVERE: Could not handle exception!
2021-01-11T15:34:07.9331170Z java.lang.IllegalArgumentException: No default error page (Status 500 or java.lang.Throwable) and no error page for type "class java.lang.NumberFormatException" defined!
2021-01-11T15:34:07.9334450Z 	at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.evaluateErrorPage(PrimeExceptionHandler.java:419)
2021-01-11T15:34:07.9339650Z 	at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handleRedirect(PrimeExceptionHandler.java:361)
2021-01-11T15:34:07.9344910Z 	at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handleAjaxException(PrimeExceptionHandler.java:214)
2021-01-11T15:34:07.9348410Z 	at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handle(PrimeExceptionHandler.java:112)
2021-01-11T15:34:07.9350900Z 	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:216)
2021-01-11T15:34:07.9352680Z 	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
2021-01-11T15:34:07.9354290Z 	at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:57)
2021-01-11T15:34:07.9357670Z 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
2021-01-11T15:34:07.9360130Z 	at org.apache.tomee.myfaces.TomEEWorkaroundFacesServlet.service(TomEEWorkaroundFacesServlet.java:47)
2021-01-11T15:34:07.9363080Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2021-01-11T15:34:07.9367710Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9369590Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2021-01-11T15:34:07.9371660Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-01-11T15:34:07.9374230Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9379250Z 	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
2021-01-11T15:34:07.9383310Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-01-11T15:34:07.9389160Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-01-11T15:34:07.9391250Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2021-01-11T15:34:07.9393140Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2021-01-11T15:34:07.9395030Z 	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
2021-01-11T15:34:07.9396780Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2021-01-11T15:34:07.9399130Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
2021-01-11T15:34:07.9401070Z 	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
2021-01-11T15:34:07.9403020Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2021-01-11T15:34:07.9404780Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2021-01-11T15:34:07.9406540Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2021-01-11T15:34:07.9408190Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
2021-01-11T15:34:07.9409830Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2021-01-11T15:34:07.9411480Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
2021-01-11T15:34:07.9412940Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
2021-01-11T15:34:07.9416230Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2021-01-11T15:34:07.9418350Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-11T15:34:07.9420080Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-11T15:34:07.9423450Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2021-01-11T15:34:07.9424540Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-11T15:34:07.9424950Z 
```

**Comment by melloware** [comment]
That was done on purpose.  I am submitting "def" to the backing bean knowing it should always be a number and rejected by the server side and thus leavin the UI submitted value at its original value.  This is basically to test someone "manipulating" the hidden input value and submiting.

**Comment by melloware** [comment]
I wonder if there is a way to detect a non 200 OK response from AJAX in `xhr.status` or something?  Because it would be nice to have an `assertRequestFailure()` method that checks whether it failed or not.

**Comment by christophs78** [comment]
Looks like even in this case HTTP 200 comes back from server. (I did not debug into this yet.)
Didn´t expect this exception show´s up in log. Personally expected wrong user input result´s in a message to the user but not in log-output. But it´s a very minor issue.
